apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
  namespace: cicd
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
      <servers>
        <server>
          <id>nexus</id>
          <username>admin</username>
          <password>admin123</password>
        </server>
      </servers>
      <mirrors>
        <mirror>
          <id>nexus</id>
          <name>nexus</name>
          <url>http://nexus.cicd.svc:8081/repository/maven-public/</url>
          <mirrorOf>*</mirrorOf>
        </mirror>
      </mirrors>
    </settings>
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: gitea-init
  namespace: cicd
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitea-init-role
  namespace: cicd
rules:
  - verbs:
    - list
    - get
    - watch
apiGroups:
  - ''
resources:
  - ''
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitea-init-dedicated-admins
  namespace: cicd
subjects:
  - kind: ServiceAccount
    name: gitea-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitea-init-role
