apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
  namespace: cicd
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
      <servers>
        <server>
          <id>nexus</id>
          <username>admin</username>
          <password>admin123</password>
        </server>
      </servers>
      <mirrors>
        <mirror>
          <id>nexus</id>
          <name>nexus</name>
          <url>http://nexus.cicd.svc:8081/repository/maven-public/</url>
          <mirrorOf>*</mirrorOf>
        </mirror>
      </mirrors>
    </settings>
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: gitea-init
  namespace: cicd
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitea-init-role
  namespace: cicd
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - gitea.pfe.rhpds.com
    resources:
      - 'gitea'
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - 'route.openshift.io'
    resources:
      - routes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - services
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitea-init-rolebinding
  namespace: cicd
subjects:
  - kind: ServiceAccount
    name: gitea-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitea-init-role

#Error from server (Forbidden): gitea.pfe.rhpds.com "gitea" is forbidden: User "system:serviceaccount:cicd:gitea-init" cannot get resource "gitea" in API group "pfe.rhpds.com" in the namespace "cicd": RBAC: clusterrole.rbac.authorization.k8s.io "dedicated-admins" not found
#Error from server (Forbidden): routes.route.openshift.io "webhook" is forbidden: User "system:serviceaccount:cicd:gitea-init" cannot get resource "routes" in API group "route.openshift.io" in the namespace "cicd": RBAC: clusterrole.rbac.authorization.k8s.io "dedicated-admins" not found
#Error from server (Forbidden): services "gitea" is forbidden: User "system:serviceaccount:cicd:gitea-init" cannot get resource "services" in API group "" in the namespace "cicd": RBAC: clusterrole.rbac.authorization.k8s.io "dedicated-admins" not found
