kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitea-init-rolebinding
  namespace: cicd
subjects:
  - kind: ServiceAccount
    name: gitea-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitea-init-role