kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: gitea-init-role
  namespace: cicd
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - pfe.rhpds.com
    resources:
      - gitea
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - operators.coreos.com
    resources:
      - operators