apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    kubernetes.io/metadata.name: dev
    argocd.argoproj.io/managed-by: openshift-gitops
  name: dev
spec:
  finalizers:
  - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-tasks
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: Applications/petclinic/tasks
    repoURL: >-
      https://github.com/nreilly-rhn/tekton-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-pipelines
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: Applications/petclinic/pipelines
    repoURL: >-
      https://github.com/nreilly-rhn/tekton-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true