apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nexus
  name: nexus-pv
  namespace: demo-cicd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi