apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    kubernetes.io/metadata.name: gitea-operator
  name: gitea-operator
spec:
  finalizers:
  - kubernetes