apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: reports-repo
  name: reports-repo-pv
  namespace: cicd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi